spring:
  datasource:
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/telegram_app"


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: e94705a0fae17d
    password: aab9f6ffa4782b
    properties:
      smtp:
        auth: true
        starttls:
          enable: true

  freemarker:
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  address: 0.0.0.0



telegram:
  channelId: -1002167921553
  botToken: 6896117366:AAGfVfyiWJ0_g4JLlayJHkFO6TTEUtQnQ-o