spring:
  datasource:
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/telegram_app"


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: e94705a0fae17d
    password: aab9f6ffa4782b
    properties:
      smtp:
        auth: true
        starttls:
          enable: true


  freemarker:
    prefix: classpath:/templates/
