spring:
  datasource:
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/telegram_app"


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  mail:
    port: 25
    host: sandbox.smtp.mailtrap.io
    username: 89f66261c8d153
    password: 132dd5a7858946



telegram:
  sender:
    botToken: 7474179192:AAFHZjuFrL-eb2mVRO-nImOZXIxwlPRxlXA
    chatId: 1808922480